### PR TITLE
4.x: Change driver.name to ScyllaDB Java Driver

### LINKED ISSUE #300: Cassandra driver_name in system.clients
Hello, 

While traversing several databases I noticed that it might be useful to see which driver used by a client.

For the current moment this value used to fill the `driver_name` column in `system.clients` table.

https://github.com/scylladb/java-driver/blob/9fe1e03f1dc5380c517f5903cb1e78689566df96/driver-core/src/main/java/com/datastax/driver/core/Requests.java#L45

This is ambiguous in situations when you're doing migration from Cassandra to Scylla.

image

Regards,
Vladimir

### PR DESCRIPTION
**Pull request by Bouncheck**
Changes the driver.name in Driver.properties file.

Fixes #300.

### CODE REVIEW

**Review by dkropachev — APPROVED** [review]

**Comment by Lorak-mmk** [comment]
@Bouncheck Here CI is failing too. Why?

**Comment by Bouncheck** [comment]
Looks like usual flakiness. Ccm failed to start at some point and testing environment got messed up.

**Comment by Lorak-mmk** [comment]
Do you have plans to work on this? I see that both 3.x and 4.x are flaky (but for different reasons).

**Review by Lorak-mmk — APPROVED** [review]

**Comment by Bouncheck** [comment]
Currently I don't but it may be worth attaching to an issue for later planning.

**Review by roydahan — APPROVED** [review]

**Comment by Lorak-mmk** [comment]
Please open such an issue. CI stability is important

**Pull request merged**
