### PR TITLE
Fix docs 404 errors

### LINKED ISSUE #86: DOCS: 404 errors
Initially reported here https://github.com/scylladb/scylla-docs/issues/3656

From this page:
https://java-driver.docs.scylladb.com/stable/manual/statements/prepared/

Are the following Broken links:
PreparedStatement
https://java-driver.docs.scylladb.com/latest/api/com/datastax/driver/core/PreparedStatement.html
BoundStatement
https://java-driver.docs.scylladb.com/latest/api/com/datastax/driver/core/BoundStatement.html
setPrepareOnAllHosts
https://java-driver.docs.scylladb.com/latest/api/com/datastax/driver/core/QueryOptions.html#setPrepareOnAllHosts-boolean-
setReprepareOnUp
https://java-driver.docs.scylladb.com/latest/api/com/datastax/driver/core/QueryOptions.html#setReprepareOnUp-boolean-

@haaawk - where should they link to?

### PR DESCRIPTION
**Pull request by dgarcia360**
Closes https://github.com/scylladb/java-driver/issues/86

conf.py sets ``smv_rename_latest_version`` to ``stable`` .
This PR changes the redirection from  ``latest`` to ``stable``.

### CODE REVIEW

**Comment by dgarcia360** [comment]
@lauranovich @haaawk Please review

**Comment by lauranovich** [comment]
@dgarcia360 can you please tell me how to review this PR. What should I see?

**Comment by dgarcia360** [comment]
1. Run ``make preview``.
2. Open http://127.0.0.1:5500/manual/statements/prepared/
3. Click on a  link reported as broken (e.g. ``PreparedStatement``):

image

4. It should redirect to:

https://java-driver.docs.scylladb.com/stable/api/com/datastax/driver/core/PreparedStatement.html

**Comment by lauranovich** [comment]
WORKS! thanks @dgarcia360 - @haaawk please merge and backport if possible to at least the most current version.

**Review by lauranovich — APPROVED** [review]

**Comment by avelanarius** [comment]
Merged: 1658c658b51780f7b601ce05f0aaa1137bd9d5e6

**Pull request closed without merging**
