### PR TITLE
Remove manuals for geotypes and graphs

### PR DESCRIPTION
**Pull request by avelanarius**
Remove manuals for geotypes and graphs (DSE-exclusive), which are unsupported by open-source Apache Cassandra or Scylla and we don't actively support or test them.

@haaawk @tzach I think this PR shows a conundrum I'm having: on the one hand we want the documentation (which we publish on Scylla website and is meant for our clients) to be more Scylla-specific. On the other hand, it's sometimes difficult to remove DSE-specific documentation (see `manual/core/integration/README.md` where I had to workaround the removed documentation and non-removed source code). Am I going too far? I'm pretty certain we don't want to remove DSE-specific code from the source code, as it would introduce problems while merging from upstream.

@haaawk @tzach Your opinions?

Refs #90

### CODE REVIEW

**Comment by avelanarius** [comment]
cc: @piodul (this is what we talked about in-person)

**Comment by tzach** [comment]
LGTM

The question is for the maintainer: who hard it will be to sync with upstream following this changes

**Review by haaawk — APPROVED** [review]
LGTM - let's clean up the documentation. But why is it on scylla-4.7.2.x not on scylla-4.x?

**Comment by avelanarius** [comment]
@haaawk I will also "forward-port" it to `scylla-4.x`. But to confirm the general idea: this is a good direction? (i.e. don't be afraid to extensively modify docs, but don't remove any DSE-specific code from the source code even at an expense of slightly awkward docs in few places)

**Comment by haaawk** [comment]
Let's do it then!

**Pull request merged**
