### PR TITLE
Clean gh-pages branch

### PR DESCRIPTION
**Pull request by dgarcia360**
@lauranovich @tzach Removes the contents already present in the gh-pages branch.

To enable GitHub pages, please follow https://github.com/dgarcia360/sphinx-scylla-theme#enabling-github-pages

### CODE REVIEW

**Comment by tzach** [comment]
@dgarcia360 can you please explain the PR? is it just about deleting all the HTML files, so they can be generated in the ph-pages branch later?

**Comment by dgarcia360** [comment]
@tzach Exactly, it's to make sure the next build does not conflict with the existing files.

We did the same for the python-driver: https://github.com/scylladb/python-driver/pull/51

**Review by tzach — APPROVED** [review]
LGTM

**Review by haaawk — CHANGES_REQUESTED** [review]
Why is .gitignore removed?

**Comment by lauranovich** [comment]
@haaawk - it gets readded (but if this is an issue let us know)

**Comment by haaawk** [comment]
I guess it's fine if it's only on gh-pages branch.

**Comment by dgarcia360** [comment]
@haaawk GitHub Actions will update automatically the ``gh-pages`` and the script won't create any of the ignored files. Do you prefer me to add the ``.gitignore`` file again?

**Comment by haaawk** [comment]
No need to add it again @dgarcia360

**Comment by lauranovich** [comment]
ok so this one is good to merge
@haaawk - please merge this so we can concentrate on #29

**Pull request merged**
