### PR TITLE
3.x: Change DRIVER_NAME to ScyllaDB Java Driver

### LINKED ISSUE #300: Cassandra driver_name in system.clients
Hello, 

While traversing several databases I noticed that it might be useful to see which driver used by a client.

For the current moment this value used to fill the `driver_name` column in `system.clients` table.

https://github.com/scylladb/java-driver/blob/9fe1e03f1dc5380c517f5903cb1e78689566df96/driver-core/src/main/java/com/datastax/driver/core/Requests.java#L45

This is ambiguous in situations when you're doing migration from Cassandra to Scylla.

image

Regards,
Vladimir

### PR DESCRIPTION
**Pull request by Bouncheck**
Fixes #300.

### CODE REVIEW

**Comment by Lorak-mmk** [comment]
@Bouncheck Why is CI failing?

**Comment by Bouncheck** [comment]
I don't know why this one happens but it also seems to be flaky CI

**Comment by Bouncheck** [comment]
There is probably some condition that causes that directory to be created or not, not sure what that is yet.

**Review by Lorak-mmk — APPROVED** [review]

**Comment by Bouncheck** [comment]
Seems that surefire is running actually 0 tests thus not generating any xml reports. Copy fails because it cannot find any file matching the pattern. I'm not sure why since I've seen this step complete successfully before.

**Review by roydahan — APPROVED** [review]

**Pull request merged**
