### PR TITLE
docs: update theme 1.3

### PR DESCRIPTION
**Pull request by dgarcia360**
Related issue https://github.com/scylladb/sphinx-scylladb-theme/issues/548

ScyllaDB Sphinx Theme 1.3 is now released 🥳 

We’ve added better redirects support and introduced numerous UI updates.

You can read more about all notable changes [here](https://sphinx-theme.scylladb.com/stable/upgrade/CHANGELOG.html#aug-2022).

## How to test this PR

1. Clone this PR. For more information, see [Cloning pull requests locally](https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally).

2. Enter the docs folder, and run:

```
make preview
````

4. Open http://http://localhost:3000 with your favorite browser. The doc should render without errors, and the version should be Sphinx Theme version (see the footer) must be ``1.3.x``:

image

### CODE REVIEW

**Comment by dgarcia360** [comment]
@avelanarius could you please review and merge this PR? Thanks!

**Comment by avelanarius** [comment]
One problem I see after the update is that the "API Documentation" link in the sidebar stopped linking to the actual Javadocs-generated pages.

**Comment by dgarcia360** [comment]
@avelanarius Sorry for the delay! I have some time now to revisit this issue.

https://github.com/scylladb/java-driver/pull/154/commits/ac5be0a34d02c7b38c77450fffda33d301f9d920 solves the issue, "API Documentation" should redirect to the JavaDoc generated in production.

**Comment by annastuchlik** [comment]
@avelanarius Could you review and merge this PR? We must be merged before we move on with the next theme versions.

**Comment by annastuchlik** [comment]
@avelanarius Thank you! The current theme is now applied.

**Pull request merged**
