### PR TITLE
ColumnMetadata: make "desc" column order case insensitive.

### PR DESCRIPTION
**Pull request by elcallio**
v3 version of change.

### CODE REVIEW

**Comment by elcallio** [comment]
ping?

**Comment by slivne** [comment]
@haaawk / @avelanarius ping

**Comment by slivne** [comment]
this is blocking a fix in sstableloader

**Review by haaawk — APPROVED** [review]
LGTM

**Comment by avelanarius** [comment]
@slivne @haaawk So should I release "now" to Maven the next version of 3.10.2 Driver (so the sstableloader in scylla-tools-java could have this new version as dependency)?

**Comment by haaawk** [comment]
No. I'm in the middle of version cleanup. Will release once I'm done.

**Pull request merged**
