### PR TITLE
RawColumn: make "desc" column order case insensitive.

### PR DESCRIPTION
**Pull request by elcallio**
v4 version of change

### CODE REVIEW

**Comment by elcallio** [comment]
ping?

**Comment by slivne** [comment]
@haaawk / @avelanarius ping

this is blocking a fix on sstableloader

**Comment by haaawk** [comment]
Is 4.9 driver used in our tools?

**Review by haaawk — APPROVED** [review]
LGTM

**Comment by avelanarius** [comment]
> Is 4.9 driver used in our tools?

A quick search through scylla-tools-java only yields usages of Java Driver 3.x, not 4.x.

**Pull request merged**
