### PR TITLE
Add Scylla Sphinx Theme 1.0

### PR DESCRIPTION
**Pull request by dgarcia360**
Replaces https://github.com/scylladb/java-driver/pull/101

Related issue https://github.com/scylladb/sphinx-scylladb-theme/issues/133

Sphinx ScyllaDB Theme 1.0 is now released 🥳 

We’ve made a number of updates to the look and feel of the theme to improve the overall user experience.
You can read more about all notable changes [here](https://sphinx-theme.scylladb.com/stable/CHANGELOG#september-2021).

This PR also cleans the file ``conf.py``, removing several unsued options.

## How to test this PR

1. Clone this PR. For more information, see [Cloning pull requests locally](https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally).

2. Enter the docs folder, and run:

```
make preview
````

3. Open http://127.0.0.1:5500/ with your favorite browser. You will see the docs with the new look and feel:

### CODE REVIEW

**Comment by dgarcia360** [comment]
@tzach @haaawk  @avelanarius Please review and merge with the option "Squash and merge". Thanks!

**Review by tzach — APPROVED** [review]
LGTM

**Comment by tzach** [comment]
ping

**Review by avelanarius — APPROVED** [review]

**Comment by tzach** [comment]
@dgarcia360 @avelanarius I do not see a release drop down
https://docs.scylladb.com/using-scylla/drivers/cql-drivers/scylla-java-driver/

I think we had it before (not sure)

**Comment by avelanarius** [comment]
@tzach This is different documentation - it's Scylla's documentation, not the driver's documentation. The driver's documentation (https://java-driver.docs.scylladb.com/) has the release drop down.

**Comment by tzach** [comment]
Aha! my bad :eyes:

**Pull request merged**
