### PR TITLE
Deps: update Netty to 4.1.109

### PR DESCRIPTION
**Pull request by mykaul**
Fixes: https://github.com/scylladb/java-driver/issues/288

### CODE REVIEW

**Comment by mykaul** [comment]
It's failing against Cassandra, with NPEs and such - is that a stable CI (and my change here is responsible for it) ?

**Comment by roydahan** [comment]
@Bouncheck / @k0machi are these 2 failures known to us (they look familiar to me):

```
Error:  Failures: 
Error:    DefaultLoadBalancingPolicyIT.should_apply_node_filter:252 expected:<[4]> but was:<[3]>
Error:    DefaultLoadBalancingPolicyIT.should_use_round_robin_on_local_dc_when_not_enough_routing_information:140 expected:<...e(endPoint=/127.0.0.[2:9042, hostId=6e3517ea-3c17-4fac-bdb2-707bcb488050, hashCode=1d6df1a4])> but was:<...e(endPoint=/127.0.0.[1:9042, hostId=9fdc4d7d-7a54-4971-a977-9544b4fef53b, hashCode=13aa0da1])>
[INFO] 
```

**Comment by mykaul** [comment]
@Bouncheck , @roydahan - anything I need to do here to move forward?

**Comment by roydahan** [comment]
@mykaul no, it's on @Bouncheck.

**Review by Bouncheck — APPROVED** [review]
Change itself LGTM. The DefaultLoadBalancingPolicyIT failures are flaky and seem to have common cause which is one of the nodes failing. This causes expected outputs in both methods to be different.

**Pull request merged**
