### PR TITLE
Deps: update org.bouncycastle components from 1.76 to 1.78.1

### LINKED ISSUE #286: Update deps for Scylla 3.x Java driver
bcprov-jdk18on 1.76 -> 1.78

### PR DESCRIPTION
**Pull request by mykaul**
Fixes: https://github.com/scylladb/java-driver/issues/286

### CODE REVIEW

**Comment by mykaul** [comment]
Scylla 5.3.0-rc0 (?!) failure:
```
Error:  com.datastax.driver.core.LoadBalancingPolicyBootstrapTest.beforeTestMethod[public void com.datastax.driver.core.LoadBalancingPolicyBootstrapTest.should_init_policy_with_up_contact_points() throws java.lang.Exception](0)  Time elapsed: 29.654 s  <<< FAILURE!
java.lang.AssertionError: The command ccm start  --config-dir=/tmp/1714027767534-0 failed to execute
	at com.datastax.driver.core.CCMTestsSupport.initTestContext(CCMTestsSupport.java:1013)
	at com.datastax.driver.core.CCMTestsSupport.beforeTestMethod(CCMTestsSupport.java:688)
	at com.datastax.driver.core.CCMTestsSupport.beforeTestMethod(CCMTestsSupport.java:673)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:653)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:151)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:192)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:93)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
```

5.2.17 failure:
```
Error:  Tests run: 1275, Failures: 1, Errors: 0, Skipped: 652, Time elapsed: 2,470.768 s <<< FAILURE! - in TestSuite
Error:  com.datastax.driver.core.policies.DCAwareRoundRobinPolicyTest.should_use_remote_hosts_for_local_cl_when_allowed[LOCAL_ONE](9)  Time elapsed: 0.079 s  <<< FAILURE!
org.junit.ComparisonFailure: [Expected node 2:1 to be queried 10 times but was 11] expected:<1[0]> but was:<1[1]>
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at com.datastax.driver.core.QueryTracker.assertQueried(QueryTracker.java:136)
	at com.datastax.driver.core.policies.DCAwareRoundRobinPolicyTest.should_use_remote_hosts_for_local_cl_when_allowed(DCAwareRoundRobinPolicyTest.java:312)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:200)
	at org.jboss.byteman.contrib.bmunit.BMNGAbstractRunner.run(BMNGAbstractRunner.java:56)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:212)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:707)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:151)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:192)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:93)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
```

2024.1.3 failure (same as 5.2.x above?):
```
Error:  Tests run: 1275, Failures: 1, Errors: 0, Skipped: 652, Time elapsed: 2,006.598 s <<< FAILURE! - in TestSuite
Error:  com.datastax.driver.core.policies.DCAwareRoundRobinPolicyTest.should_only_use_remote_hosts_when_using_non_dc_local_cl[LOCAL_QUORUM](7)  Time elapsed: 0.077 s  <<< FAILURE!
java.lang.AssertionError: 

Expecting:
 <com.datastax.driver.core.exceptions.TransportException: [/127.0.1.1:38287] Connection has been closed>
to be an instance of:
 <com.datastax.driver.core.exceptions.NoHostAvailableException>
but was instance of:
 <com.datastax.driver.core.exceptions.TransportException>
	at com.datastax.driver.core.QueryTracker.query(QueryTracker.java:108)
	at com.datastax.driver.core.QueryTracker.query(QueryTracker.java:72)
	at com.datastax.driver.core.policies.DCAwareRoundRobinPolicyTest.should_only_use_remote_hosts_when_using_non_dc_local_cl(DCAwareRoundRobinPolicyTest.java:253)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:200)
	at org.jboss.byteman.contrib.bmunit.BMNGAbstractRunner.run(BMNGAbstractRunner.java:56)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:212)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:707)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:151)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:192)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:93)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)

[INFO] 
[INFO] Results:
[INFO] 
Error:  Failures: 
Error:    DCAwareRoundRobinPolicyTest.should_only_use_remote_hosts_when_using_non_dc_local_cl:253 
Expecting:
 <com.datastax.driver.core.exceptions.TransportException: [/127.0.1.1:38287] Connection has been closed>
to be an instance of:
 <com.datastax.driver.core.exceptions.NoHostAvailableException>
but was instance of:
 <com.datastax.driver.core.exceptions.TransportException>
[INFO] 
Error:  Tests run: 983, Failures: 1, Errors: 0, Skipped: 360
```

**Comment by roydahan** [comment]
@Bouncheck probably we need to fix the CI.

**Comment by mykaul** [comment]
@Bouncheck , @roydahan - ping

**Comment by mykaul** [comment]
> @Bouncheck , @roydahan - ping

re-ping @Bouncheck , @roydahan  - do I need to re-run CI?

**Comment by Bouncheck** [comment]
Yes please. All 3 are likely flaky and do not reproduce locally for me. I don't have a fix for that right now but it does not look like the version bump is breaking anything.

**Comment by mykaul** [comment]
> Yes please. All 3 are likely flaky and do not reproduce locally for me. I don't have a fix for that right now but it does not look like the version bump is breaking anything.

OK, how do I do that, besides pushing an empty commit?

**Comment by Bouncheck** [comment]
> OK, how do I do that, besides pushing an empty commit?

I'm not sure myself since I do not have permissions, but IIRC in run details there should be three dots button on top right (with alt text: Workflow run options), right above the log output and I think the option to rerun should be there.

**Comment by Bouncheck** [comment]
It seems there should also be a "reload"-like looking button next to the job names on the left according to this
https://docs.github.com/en/actions/managing-workflow-runs/re-running-workflows-and-jobs#re-running-a-specific-job-in-a-workflow

**Comment by mykaul** [comment]
Rebased and pushed, let's see.

**Comment by mykaul** [comment]
Unit tests succeed, but it fails to copy results:
```
[INFO] Reactor Summary for Java Driver for Scylla and Apache Cassandra 3.11.5.3-SNAPSHOT:
[INFO] 
[INFO] Java Driver for Scylla and Apache Cassandra ........ SUCCESS [  3.735 s]
[INFO] Java Driver for Scylla and Apache Cassandra - Core . SUCCESS [ 18.139 s]
[INFO] Java Driver for Scylla and Apache Cassandra - Object Mapping SUCCESS [  1.843 s]
[INFO] Java Driver for Scylla and Apache Cassandra - Extras SUCCESS [  1.379 s]
[INFO] Java Driver for Scylla and Apache Cassandra - Examples SUCCESS [  1.536 s]
[INFO] Java Driver for Scylla and Apache Cassandra Tests .. SUCCESS [  0.004 s]
[INFO] Java Driver for Scylla and Apache Cassandra Tests - Stress SUCCESS [  0.245 s]
[INFO] Java Driver for Scylla and Apache Cassandra Tests - OSGi SUCCESS [  1.863 s]
[INFO] Java Driver for Scylla and Apache Cassandra Tests - OSGi - Shaded SUCCESS [  0.380 s]
[INFO] Java Driver for Scylla and Apache Cassandra Tests - OSGi - Shaded SUCCESS [  0.480 s]
[INFO] Java Driver for Scylla and Apache Cassandra Tests - OSGi - Unshaded SUCCESS [  0.470 s]
[INFO] Java Driver for Scylla and Apache Cassandra Tests - Shading SUCCESS [  0.005 s]
[INFO] Java Driver for Scylla and Apache Cassandra Tests - Shading - Shaded SUCCESS [  0.053 s]
[INFO] Java Driver for Scylla and Apache Cassandra Tests - Shading - Unshaded SUCCESS [  0.047 s]
[INFO] Java Driver for Scylla and Apache Cassandra - Binary distribution SUCCESS [  0.013 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  36.867 s
[INFO] Finished at: 2024-05-07T10:10:00Z
[INFO] ------------------------------------------------------------------------

```

CC @roydahan

**Comment by roydahan** [comment]
@avelanarius / @Bouncheck do we need to do it also in 4.x branch?

**Comment by Bouncheck** [comment]
I don't think so, since 4.x does not have those dependencies at the moment.

**Pull request merged**
