### PR TITLE
Add test method for empty pages

### LINKED ISSUE #254: Wrong handling of multiple consecutive empty pages in Java Driver 4.x
When Scylla returns multiple consecutive empty pages, Java Driver 4.x doesn't handle it correctly. Reproducer:
```java
CqlSession cqlSession = CqlSession.builder()
        .addContactPoint(InetSocketAddress.createUnresolved("127.0.0.2", 9042))
        .withLocalDatacenter("datacenter1").build();

cqlSession.execute("CREATE KEYSPACE IF NOT EXISTS ks WITH REPLICATION = {'class': 'SimpleStrategy', 'replication_factor': 1}");

cqlSession.execute("CREATE TABLE IF NOT EXISTS ks.t (pk int, ck int, v int, PRIMARY KEY(pk, ck))");

for (int i = 0; i < 50; i++) {
    System.out.println("Insert " + i);
    cqlSession.execute("INSERT INTO ks.t(pk, ck, v) VALUES (?, ?, ?)", i, i, 15);
    cqlSession.execute("INSERT INTO ks.t(pk, ck, v) VALUES (?, ?, ?)", i, i, 32);
}

cqlSession.execute("INSERT INTO ks.t(pk, ck, v) VALUES (?, ?, ?)", 8, 8, 14);
cqlSession.execute("INSERT INTO ks.t(pk, ck, v) VALUES (?, ?, ?)", 11, 11, 14);
cqlSession.execute("INSERT INTO ks.t(pk, ck, v) VALUES (?, ?, ?)", 14, 14, 14);

SimpleStatement st = SimpleStatement.newInstance("SELECT * FROM ks.t WHERE v = 14 ALLOW FILTERING");
st = st.setPageSize(1);

cqlSession.execute(st).all().forEach(r -> {
    System.out.println(r);
});
cqlSession.close();
```

The code is supposed to print 3 rows, but it doesn't print anything.

### PR DESCRIPTION
**Pull request by Bouncheck**
Adds a test method to SimpleStatementCcmIT that checks if SimpleStatement with page size 1 correctly fetches all rows.

Fixes #254

### CODE REVIEW

**Comment by roydahan** [comment]
1 check is still failing.

**Comment by roydahan** [comment]
[INFO] Results:
[INFO] 
Error:  Failures: 
Error:    DefaultLoadBalancingPolicyIT.should_apply_node_filter:252 expected:<[4]> but was:<[3]>
Error:    DefaultLoadBalancingPolicyIT.should_use_round_robin_on_local_dc_when_not_enough_routing_information:140 expected:<...e(endPoint=/127.0.0.[3:9042, hostId=42d20587-0733-4a6b-8971-bbeb6ea22d53, hashCode=7c4139df])> but was:<...e(endPoint=/127.0.0.[2:9042, hostId=e32313f3-c9e7-4a78-a71c-02a40d48657f, hashCode=3d7c33e4])>
Error:  Errors: 
Error:    AddedNodeIT.should_signal_and_create_pool_when_node_gets_added:70 » ConditionTimeout
[INFO] 
Error:  Tests run: 125, Failures: 2, Errors: 1, Skipped: 37

**Comment by avelanarius** [comment]
Debugging the failing test, it doesn't seem to reproduce localy.

**Comment by avelanarius** [comment]
The `ConditionTimeout` error I can reproduce when using `master` CCM, doesn't reproduce for me with older CCM.

**Comment by avelanarius** [comment]
The test (that was failing with `ConditionTimeout`) passes if I change the timeout to 120 second (from 60 seconds).

Maybe the newer version of CCM doesn't correctly configure the cluster which results in a longer startup time.

**Comment by avelanarius** [comment]
Bisecting CCM yields this commit: https://github.com/scylladb/scylla-ccm/commit/dd9ff60dc05b34c5efa63de5bd15216b890216c1

> ccmlib: stop passing auto_bootstrap
> we stopped handling auto_bootstrap since
> https://github.com/scylladb/scylladb/commit/3b1ff90 and the behavior is like it's true, so stop
> passing this setting down.

**Comment by avelanarius** [comment]
Trying if the tests pass on Github CI with older CCM.

**Comment by avelanarius** [comment]
The test pass with older CCM, https://github.com/scylladb/scylla-ccm/pull/550 will fix the master CCM.

**Comment by roydahan** [comment]
CCM PR was merged.
All checks passed.

**Pull request merged**
