### PR TITLE
docs: update theme 1.5

### PR DESCRIPTION
**Pull request by dgarcia360**
Related issue https://github.com/scylladb/sphinx-scylladb-theme/issues/707

ScyllaDB Sphinx Theme 1.4 is now released 🥳 

You can read more about all notable changes [here](https://sphinx-theme.scylladb.com/master/upgrade/CHANGELOG.html#march-2023).

## How to test this PR

1. Clone this PR. For more information, see [Cloning pull requests locally](https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally).

2. Enter the docs folder, and run:

  ```
  make preview
  ````

3. Open http://localhost:5500 with your favorite browser. The doc should render without errors, and the version should be Sphinx Theme version (see the footer) must be ``1.4.x``:

image

### CODE REVIEW

**Comment by dgarcia360** [comment]
cc/ @annastuchlik

**Comment by annastuchlik** [comment]
@avelanarius Can you merge this PR to update the Sphinx theme? The PR looks good and the failing checks seem to be test-related. Could you look into it?

**Comment by dgarcia360** [comment]
@annastuchlik @avelanarius Updated the pull request to update to 1.5. You can read more about all changes [here](https://sphinx-theme.scylladb.com/master/upgrade/CHANGELOG.html#may-2023).

**Review by annastuchlik — APPROVED** [review]
LGTM

**Comment by annastuchlik** [comment]
@avelanarius Please merge.

**Comment by annastuchlik** [comment]
@avelanarius Please merge this PR. We'd like to update the theme to 1.6, so this PR should be merged before that.

**Comment by annastuchlik** [comment]
@avelanarius ping

**Pull request merged**
