### PR TITLE
[dtest]: test_connectivity_with_cassandra_stress failed with `java.lang.NoSuchMethodError`

### PR DESCRIPTION
**Pull request by yaronkaikov**
Following the changes made in
https://github.com/scylladb/scylla-tools-java/pull/369, dtest is now failing during `test_connectivity_with_cassandra_stress` with the following error:
```
stderr: java.lang.NoSuchMethodError: 'java.lang.String com.google.common.net.HostAndPort.getHostText()'
	at com.datastax.driver.core.ScyllaCloudDatacenter.getServer(ScyllaCloudDatacenter.java:77)
	at com.datastax.driver.core.Cluster$Builder.withScyllaCloudConnectionConfig(Cluster.java:1404)
	at com.datastax.driver.core.Cluster$Builder.withScyllaCloudConnectionConfig(Cluster.java:1397)
	at com.datastax.driver.core.Cluster$Builder.withScyllaCloudConnectionConfig(Cluster.java:1393)
	at com.datastax.driver.core.Cluster$Builder.withScyllaCloudConnectionConfig(Cluster.java:1389)
	at org.apache.cassandra.stress.util.JavaDriverClient.connect(JavaDriverClient.java:181)
	at org.apache.cassandra.stress.settings.StressSettings.getJavaDriverClient(StressSettings.java:213)
	at org.apache.cassandra.stress.settings.SettingsSchema.createKeySpacesNative(SettingsSchema.java:84)
	at org.apache.cassandra.stress.settings.SettingsSchema.createKeySpaces(SettingsSchema.java:74)
	at org.apache.cassandra.stress.settings.StressSettings.maybeCreateKeyspaces(StressSettings.java:230)
	at org.apache.cassandra.stress.StressAction.run(StressAction.java:58)
	at org.apache.cassandra.stress.Stress.run(Stress.java:143)
	at org.apache.cassandra.stress.Stress.main(Stress.java:62)
```

### CODE REVIEW

**Review by muzarski — APPROVED** [review]
Please adjust the commit message so it describes introduced change. Otherwise LGTM.

**Comment by muzarski** [comment]
@Lorak-mmk could you please take a look at it?

**Comment by mykaul** [comment]
Fix https://github.com/scylladb/java-driver/blob/085dd34ef46b1de5111629bdccfe4056c4355676/driver-core/src/main/java/com/datastax/driver/core/ScyllaCloudDatacenter.java#L77
In the same way as https://github.com/scylladb/java-driver/blob/085dd34ef46b1de5111629bdccfe4056c4355676/driver-core/src/main/java/com/datastax/driver/core/GuavaCompatibility.java#L198

(And update Guava, if we haven't done so in the Java driver, and update the Java driver in scylla-tools-java  - cassandra-stress, if we haven't done so)

**Comment by yaronkaikov** [comment]
> Fix
> 
> https://github.com/scylladb/java-driver/blob/085dd34ef46b1de5111629bdccfe4056c4355676/driver-core/src/main/java/com/datastax/driver/core/ScyllaCloudDatacenter.java#L77
> 
> 
> In the same way as
> https://github.com/scylladb/java-driver/blob/085dd34ef46b1de5111629bdccfe4056c4355676/driver-core/src/main/java/com/datastax/driver/core/GuavaCompatibility.java#L198

> 
> (And update Guava, if we haven't done so in the Java driver, and update the Java driver in scylla-tools-java - cassandra-stress, if we haven't done so)

Updated `Guava` , i assume we need to update the java driver after this will be merged

**Comment by yaronkaikov** [comment]
Closed by mistake
And can't re-open so i will open a new one

**Pull request closed without merging**
