### PR TITLE
Add docs generation to scylla-4.x branch

### PR DESCRIPTION
**Pull request by avelanarius**
Ports the `docs/` directory from scylla-3.x branch. Fixes the existing documentation on scylla-4.x branch to properly generate with Sphynx: adding `.. toctree` entries, removing "hocon" code highlighting, fixing minor path/formatting issues.

This PR is to the `scylla-4.x` branch, but once approved I will commit it to all `scylla-4.*.*.*` branches.

Afterwards, I will send another PR that changes the branch list on `scylla-3.x` and GitHub Actions job, so that the documentation is actually published to the internet.

### CODE REVIEW

**Comment by avelanarius** [comment]
cc: @dgarcia360 (could not add you as a reviewer)

**Comment by haaawk** [comment]
@tzach Could you please ask @dgarcia360 to review this PR?

**Review by haaawk — APPROVED** [review]
LGTM but I'm far from being an expert on this documentation system

**Comment by haaawk** [comment]
@tzach @dgarcia360 ping

**Comment by dgarcia360** [comment]
@haaawk  Sorry, I missed this somehow 🙈 I'll review this PR asap

**Comment by dgarcia360** [comment]
@avelanarius @haaawk First off, thanks for waiting!

I'm getting the following errors when running ``makepreview`` (javadoc with JDK8):

1. 

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project java-driver-core: Compilation failure
[ERROR] /java-driver/core/src/main/java/com/datastax/oss/driver/internal/core/channel/OutboundTrafficMeter.java:[27,8] cannot access > java.lang.Object
[ERROR]   bad class file: /modules/java.base/java/lang/Object.class
[ERROR]     class file has wrong version 61.0, should be 53.0
[ERROR]     Please remove or make sure it appears in the correct subdirectory of the classpath.
```
This error seems related to the JDK version used, but Java 8 is listed as the [minimum requirement](https://github.com/scylladb/java-driver/tree/4.x#compatibility).

2. 

```
[ERROR] /java-driver/core/src/main/java/com/datastax/oss/driver/api/core/CqlIdentifier.java:44: error: attribute not  supported in HTML5: summary
[ERROR]  * <table summary="examples">

[ERROR] /java-driver/core/src/main/java/com/datastax/oss/driver/api/core/paging/OffsetPager.java:47: error: heading used 
out of sequence: <H3>, compared to implicit preceding heading: <H1>
[ERROR]  * <h3>Performance considerations</h3>
```
After an H1, it shoud go an H2 tag. You could either fix the code or deactivate the docs linter as explained in [How to work around the stricter Java 8 Javadoc when using Maven](https://stackoverflow.com/a/34808603).

3. 

```
[ERROR] /java-driver/core/src/main/java/com/datastax/oss/driver/api/core/type/reflect/GenericType.java:353: error: unknown > tag: leaks-private-api
[ERROR]    * @leaks-private-api
[ERROR] /java-driver/core/src/main/java/com/datastax/oss/driver/api/core/metrics/Metrics.java:41: error: unknown tag: leaks
private-api
[ERROR]    * @leaks-private-api
```

Since Java 8 "unknown tag" has become an error instead of a warning. You can fix this by adding the tags to the configuration of the Javadoc process. Here's an [example](http://www.miredot.com/docs/faq/q/javadoc-fails-with-java-8/).

**Comment by dgarcia360** [comment]
> Afterwards, I will send another PR that changes the branch list on scylla-3.x and GitHub Actions job, so that the documentation is actually published to the internet.

Sounds good! Still, I believe you owuld benefit from having a branch with a name that does not change (e.g. master, main, develop) with the latest version of the software:

image

If you need to work on a new version that's forked from the DataStax repository, you could apply the changes to this branch first (master), and then create a branch for the specific release (e.g. branch-4.0)

By doing so, you would have only branch that defines which versions of the docs must be generated.

**Comment by avelanarius** [comment]
> @avelanarius @haaawk First off, thanks for waiting!
> 
> I'm getting the following errors when running `makepreview` (javadoc with JDK8):
> 
> 
> ```
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project java-driver-core: Compilation failure
> [ERROR] /java-driver/core/src/main/java/com/datastax/oss/driver/internal/core/channel/OutboundTrafficMeter.java:[27,8] cannot access > java.lang.Object
> [ERROR]   bad class file: /modules/java.base/java/lang/Object.class
> [ERROR]     class file has wrong version 61.0, should be 53.0
> [ERROR]     Please remove or make sure it appears in the correct subdirectory of the classpath.
> ```
> 
> This error seems related to the JDK version used, but Java 8 is listed as the [minimum requirement](https://github.com/scylladb/java-driver/tree/4.x#compatibility).
> 
> 
> ```
> [ERROR] /java-driver/core/src/main/java/com/datastax/oss/driver/api/core/CqlIdentifier.java:44: error: attribute not  supported in HTML5: summary
> [ERROR]  * <table summary="examples">
> 
> [ERROR] /java-driver/core/src/main/java/com/datastax/oss/driver/api/core/paging/OffsetPager.java:47: error: heading used 
> out of sequence: <H3>, compared to implicit preceding heading: <H1>
> [ERROR]  * <h3>Performance considerations</h3>
> ```
> 
> After an H1, it shoud go an H2 tag. You could either fix the code or deactivate the docs linter as explained in [How to work around the stricter Java 8 Javadoc when using Maven](https://stackoverflow.com/a/34808603).
> 
> 
> ```
> [ERROR] /java-driver/core/src/main/java/com/datastax/oss/driver/api/core/type/reflect/GenericType.java:353: error: unknown > tag: leaks-private-api
> [ERROR]    * @leaks-private-api
> [ERROR] /java-driver/core/src/main/java/com/datastax/oss/driver/api/core/metrics/Metrics.java:41: error: unknown tag: leaks
> private-api
> [ERROR]    * @leaks-private-api
> ```
> 
> Since Java 8 "unknown tag" has become an error instead of a warning. You can fix this by adding the tags to the configuration of the Javadoc process. Here's an [example](http://www.miredot.com/docs/faq/q/javadoc-fails-with-java-8/).

@dgarcia360 Could you specify which version of Java 8 you are using? I just tested it in a fresh Ubuntu Docker container with only Java 8 installed and I'm not getting any of those errors.

My version:
```
java -version
openjdk version "1.8.0_312"
OpenJDK Runtime Environment (build 1.8.0_312-8u312-b07-0ubuntu1~20.04-b07)
OpenJDK 64-Bit Server VM (build 25.312-b07, mixed mode)
```

**Comment by avelanarius** [comment]
> Sounds good! Still, I believe you owuld benefit from having a branch with a name that does not change (e.g. master, main, develop) with the latest version of the software:

`scylla-3.x` and `scylla-4.x` are those types of branches (name does not change) - there won't be `5.x`, `6.x`, ... anytime soon. Those branches could be essentially called `scylla-legacy-version`, `scylla-modernized-version` (3.x and 4.x refer to two dramatically different driver implementations).

**Comment by dgarcia360** [comment]
@avelanarius 

LGTM!

> Could you specify which version of Java 8 you are using?

My fault, it seems I was using Java 11. I've reinstalled Java 8 and run the command and now I don't get any errors.

**Comment by avelanarius** [comment]
> My fault, it seems I was using Java 11. I've reinstalled Java 8 and run the command and now I don't get any errors.

I'll try running it with Java 11 later this week - it should also build/generate docs correctly with Java 11 and the errors you posted previously looked valid (but didn't know how to reproduce them).

**Comment by avelanarius** [comment]
I was able to reproduce the Java11 issue with a fresh Ubuntu Docker container with only Oracle's `jdk-11.0.14_linux-x64_bin.deb` installed.

I might still decide to merge this PR as-is now and tackle this problem later. Created issues #117 and #118.

**Comment by annastuchlik** [comment]
> This PR is to the scylla-4.x branch, but once approved I will commit it to all scylla-4.*.*.* branches.

> Afterwards, I will send another PR that changes the branch list on scylla-3.x and GitHub Actions job, so that the documentation is actually published to the internet.

@avelanarius Cloud you open the PR you mentioned above? This is a prerequisite to moving on with the Sphinx theme updates (this project is behind other projects and should be synced).

**Comment by avelanarius** [comment]
@annastuchlik I have backported this PR (docs generation on 4.x) to all `scylla-4.*x` branches. I have pushed a commit (34722c943e28d29e63cfa99855f42086f85f1ac4) that all 3.x branches are published. I have fixed problem of building the docs (cdaf75a6cf54b91f3f795aa509cf836166dad1e2).

**Comment by annastuchlik** [comment]
@avelanarius Thank you so much!
@dgarcia360 Can we move on now?

**Pull request merged**
