### PR TITLE
docs: wrap long line for better readability

### PR DESCRIPTION
**Pull request by tchaikov**

### CODE REVIEW

**Comment by tchaikov** [comment]
since the 3.x is more "master" than 4.x, i am targeting the former. please let me know if i should target 4.x..

**Comment by roydahan** [comment]
PR need to be rebased.

**Comment by tchaikov** [comment]
rebased and repushed.

**Comment by roydahan** [comment]
1 check fails for  scylla-5.3.0-rc0, which doesn't exist.
@avelanarius we need to remove this version.

**Review by roydahan — APPROVED** [review]

**Comment by tchaikov** [comment]
thanks Roy!

**Pull request merged**
