### PR TITLE
Merge 4.18.0

### PR DESCRIPTION
**Pull request by Bouncheck**
Adding most of the changes from last merge up to 4.18.0 with slight modifications to resolve conflicts.

### CODE REVIEW

**Comment by Bouncheck** [comment]
There are 2 new modules that I've removed after conflict resolution, but maybe I should've just renamed their groupId to com.scylladb? Specifically `distribution-tests` and `distribution-source`.

This is very likely not ready for merge because I could've merged in something that did not really conflict with anything but should not be merged in anyway.

From what I've seen most of the conflicts were due to: 
- Changes to LICENSE files. They were renamed, modified and added as resources in several pom.xml
- Changes to license headers, because upstream is now apache instead of datastax
- Changes in README files. Mostly differences in maven groupIds but also some small changes like new instructions how to exclude/include JARs for annotations.
- Different plugin versions and sets of plugins used. Most of upstream additions were discarded. Changes to scope of some plugins.
- Unification of some version requirement annotations into BackendRequirement annotation and subsequent changes to tests and test rules.

**Comment by Bouncheck** [comment]
On another look I don't see anything besides `.asf.yaml` that should be deleted. Rest of the files seem to be already present in `scylla-4.x` branch

**Comment by Bouncheck** [comment]
Some of the tests are failing, I still need to look into that.

**Comment by Bouncheck** [comment]
I think this is ready to merge, but needs to be reviewed.
Is version 4.18.0.0-SNAPSHOT correct here?

**Comment by roydahan** [comment]
@avelanarius please give high priority for review

**Pull request merged**
