### PR TITLE
docs: add default branch

### PR DESCRIPTION
**Pull request by dgarcia360**
Adds default branch to the docs fix the "Edit this page" button.

### CODE REVIEW

**Review by Bouncheck — DISMISSED** [review]
Branch change itself LGTM, but on several pages the path does not resolve to correct files for me.
For example for load balancing manual I get https://github.com/scylladb/java-driver/edit/scylla-3.x/docs/source/manual/load_balancing/index.md
while I assume I should end up on https://github.com/scylladb/java-driver/edit/scylla-3.x/manual/load_balancing/README.md
This seems like a separate issue though so I'm approving the branch change.

**Comment by Lorak-mmk** [comment]
What about the driver 4.x? Will the edit button just not work for it?

**Comment by Bouncheck** [comment]
I'm assuming that for 4.x we need similar PR for scylla-4.x branch

**Comment by Bouncheck** [comment]
Maybe that's wrong assumption though. How is final documentation page created? I'm not sure who maintains it. Is it a result of `make multiversion` or is it a combination of a build made on 3.x branch and a separate one on 4.x branch? Because in `make multiversionpreview` it does indeed result in pointing to 3.x branch for 4.x versions too.

**Comment by Bouncheck** [comment]
It seems that on 4.x branch the docs directory is a copy of 3.x one. Looks like one made for convenience sake and that we do not maintain different configuration for 4.x. So if we create multi version (including 4.x) documentation from 3.x branch we should not be defaulting to 3.x urls for all versions. Thanks for the catch @Lorak-mmk.

**Comment by dkropachev** [comment]
@dgarcia360 , could you please take a look at https://github.com/scylladb/sphinx-scylladb-theme/issues/1156 before merging it.

**Comment by dgarcia360** [comment]
Replaced by https://github.com/scylladb/java-driver/pull/367

**Pull request closed without merging**
