### PR TITLE
Connect to server specified in serverless bundle

### LINKED ISSUE #164: [serverless] connection should be only open with `server`
Running recent cassandra-stress (that uses java-driver with sni_proxy support)
with a local setup kind of scylla-operator 
```
docker run -it --network=host -v /home/fruch/Downloads/k8s_config.yaml:/k8s_config.yaml --entrypoint=/bin/bash scylladb/scylla-nightly cassandra-stress write -cloudconf file=/k8s_config.yaml -log interval=5
```

```
cat /etc/hosts

127.0.0.1       localhost
127.0.1.1       fruch-scylla

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters

10.96.121.188 any.cql.fruch.scylladb.com
#10.96.121.188 c0e65e5c-38d1-431d-8e9f-d9dd5af9854f.cql.fruch.scylladb.com
#10.96.121.188 dd4e15e6-fcb0-46b1-af88-8a010a6161ed.cql.fruch.scylladb.com
#10.96.121.188 0d56abe0-91f9-43ee-9b39-4536488b6089.cql.fruch.scylladb.com
```

fails when it's trying to do DNS resolving of the nodes, which it shouldn't be doing, on the `any.cql.*` address should be connected to:
```

Connected to cluster: sct-cluster, max pending requests per connection null, max connections per host 8
java.lang.RuntimeException: java.lang.IllegalArgumentException: Could not resolve proxy address c0e65e5c-38d1-431d-8e9f-d9dd5af9854f.cql.fruch.scylladb.com
        at org.apache.cassandra.stress.settings.StressSettings.getJavaDriverClient(StressSettings.java:223)
        at org.apache.cassandra.stress.settings.SettingsSchema.createKeySpacesNative(SettingsSchema.java:79)
        at org.apache.cassandra.stress.settings.SettingsSchema.createKeySpaces(SettingsSchema.java:69)
        at org.apache.cassandra.stress.settings.StressSettings.maybeCreateKeyspaces(StressSettings.java:231)
        at org.apache.cassandra.stress.StressAction.run(StressAction.java:58)
        at org.apache.cassandra.stress.Stress.run(Stress.java:143)
        at org.apache.cassandra.stress.Stress.main(Stress.java:62)
Caused by: java.lang.IllegalArgumentException: Could not resolve proxy address c0e65e5c-38d1-431d-8e9f-d9dd5af9854f.cql.fruch.scylladb.com
        at com.datastax.driver.core.SniEndPoint.resolve(SniEndPoint.java:68)
        at com.datastax.driver.core.Host.getAddress(Host.java:196)
        at org.apache.cassandra.stress.util.JavaDriverClient.connect(JavaDriverClient.java:191)
        at org.apache.cassandra.stress.settings.StressSettings.getJavaDriverClient(StressSettings.java:214)
        ... 6 more
Caused by: java.net.UnknownHostException: c0e65e5c-38d1-431d-8e9f-d9dd5af9854f.cql.fruch.scylladb.com: Name or service not known
        at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
        at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:929)
        at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1529)
        at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:848)
        at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1519)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1378)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1306)
        at com.datastax.driver.core.SniEndPoint.resolve(SniEndPoint.java:55)
        ... 9 more
```

> We (@tnozicka) talked with 
@zimnx 
 and all traffic should go to the server. Contrary to or initial design, and to comply with meaning of the fields we have, the operator is not gonna use the any.cql.clusterName... prefix in the future but only cql.clusterName... for the load balanced endpoint. So technically only cql.clusterName... has to be resolvable. The infra will have it setup as a wildcard anyways.
This will make it be in line with how TLS.ServerName behaves. The change is to remove tlsServerName field from the config, that is fully covered in the nodeDomain field that acts as TLS.ServerName suffix. This won't need a driver change as it's only in the operator.

### LINKED ISSUE #167: [serverless] should connect to Server specified in ConnectionConfig and use NodeDomain as SNI.
with this configuration:
```yaml
...
datacenters:
  dc-1:
    certificateAuthorityData: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZHakNDQXdLZ0F3SUJBZ0lRZEJ3R1p4a1JKdG5jc01uN2R3eXBJVEFOQmdrcWhraUc5dzBCQVEwRkFEQW4KTVNVd0l3WURWUVFERXh4elkzUXRZ>
    nodeDomain: cql.sct-cluster.sct.scylladb.com
    server: 10.92.10.33:9142
...
```

we are failing like the following:
```
DEBUG    RemoteCmdRunner:base.py:150 STDERR: WARN  13:41:57,068 Error creating netty channel to 10.96.30.25:9142:10.96.30.25
com.datastax.shaded.netty.channel.ConnectTimeoutException: connection timed out: /10.96.30.25:9142
	at com.datastax.shaded.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:261)
	at com.datastax.shaded.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at com.datastax.shaded.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
	at com.datastax.shaded.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at com.datastax.shaded.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at com.datastax.shaded.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
	at com.datastax.shaded.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at com.datastax.shaded.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at com.datastax.shaded.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
java.lang.RuntimeException: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: 10.96.30.25:9142:10.96.30.25 (com.datastax.driver.core.exceptions.TransportException: [10.96.30.25:9142:10.96.30.25] Cannot connect))
	at org.apache.cassandra.stress.settings.StressSettings.getJavaDriverClient(StressSettings.java:223)
	at org.apache.cassandra.stress.settings.SettingsSchema.createKeySpacesNative(SettingsSchema.java:79)
	at org.apache.cassandra.stress.settings.SettingsSchema.createKeySpaces(SettingsSchema.java:69)
	at org.apache.cassandra.stress.settings.StressSettings.maybeCreateKeyspaces(StressSettings.java:231)
	at org.apache.cassandra.stress.StressAction.run(StressAction.java:58)
	at org.apache.cassandra.stress.Stress.run(Stress.java:143)
	at org.apache.cassandra.stress.Stress.main(Stress.java:62)
Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: 10.96.30.25:9142:10.96.30.25 (com.datastax.driver.core.exceptions.TransportException: [10.96.30.25:9142:10.96.30.25] Cannot connect))
	at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:275)
	at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:114)
	at com.datastax.driver.core.Cluster$Manager.negotiateProtocolVersionAndConnect(Cluster.java:1843)
	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1757)
	at com.datastax.driver.core.Cluster.getMetadata(Cluster.java:475)
	at org.apache.cassandra.stress.util.JavaDriverClient.connect(JavaDriverClient.java:182)
	at org.apache.cassandra.stress.settings.StressSettings.getJavaDriverClient(StressSettings.java:214)
	... 6 more
```

Instead it should connect to Server specified in ConnectionConfig and use NodeDomain as SNI.

See PRs in the other driver to align on how we want it to behave:
https://github.com/scylladb/python-driver/pull/177
https://github.com/scylladb/gocql/pull/106

### LINKED ISSUE #169: Driver sometimes connects to "any.cluster-id.scylla.com" endpoint in integration tests
```
    29877  [cluster1-nio-worker-0] WARN  com.datastax.driver.core.Connection - Error creating netty channel to any.cluster-id.scylla.com:35617:any.cluster-id.scylla.com
io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: Brak trasy do hosta: any.cluster-id.scylla.com/185.100.131.102:35617
Caused by: java.net.NoRouteToHostException: Brak trasy do hosta
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:716)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:750)
```

### PR DESCRIPTION
**Pull request by avelanarius**
Before this change, the driver, when connecting to a serverless cluster,
would try to resolve `host-id.*` domains as a proxy IP for each node.

This commit aligns the behavior with scylladb/python-driver#177 and
scylladb/gocql#106. Now, the "Server" field of bundle is the single
hostname/IP the driver will use for proxy connection.

This simplifies the setup we had in integration tests, removing the
necessity of hacks to work around previous behavior (driver trying to
resolve host-id.* domains).

Fixes #164
Fixes #167
Fixes #169

### CODE REVIEW

**Comment by avelanarius** [comment]
(PR based on top of https://github.com/scylladb/java-driver/pull/171 PR)

**Comment by avelanarius** [comment]
5.1.0-rc4 and 2022.2.0-rc4 fail due to: https://github.com/scylladb/scylladb/issues/11945 (on unrelated test)

**Review by fruch — APPROVED** [review]
LGTM

**Comment by fruch** [comment]
@avelanarius ping, we need this for testing with c-s, without it it might be hard for us to start testing longevity

**Comment by avelanarius** [comment]
@fruch Merged, next I will release the driver and bump the version in scylla-tools-java.

**Pull request merged**
