### PR TITLE
added training information and links to Scylla University in readme file

### PR DESCRIPTION
**Pull request by guy9**
@tzach please review

### CODE REVIEW

**Comment by tzach** [comment]
I suggest to replace the datastax academy link with Scylla U link

**Comment by guy9** [comment]
@tzach thanks, done. I only touched training related parts of the file as I saw @lauranovich is already working on the file and has a draft ready.

**Comment by guy9** [comment]
ping

**Comment by guy9** [comment]
@haaawk can you please review this?

**Comment by haaawk** [comment]
This is a wrong branch @guy9 we need those changes in 3.10.2-scylla and 4.9.0-scylla

**Comment by guy9** [comment]
Replaced by PR #39 and PR #40

**Pull request closed without merging**
