### PR TITLE
Serverless support for version 4.x

### PR DESCRIPTION
**Pull request by Bouncheck**
Enables basic support for serverless Scylla clusters.
Changes include:

- Necessary core code changes
- Slight changes to test utilities and new tests
- Removal of code parts related to Datastax Astra

Tested with both remote clusters and CCM with SNI proxy locally.

### CODE REVIEW

**Comment by avelanarius** [comment]
This error in integration tests looks a bit worrying:

```
com.datastax.oss.driver.api.core.AllNodesFailedException: Could not reach any contact point, make sure you've provided valid addresses (showing first 1 nodes, use getAllErrors() for more): Node(endPoint=127.0.0.1:443:cql.cluster-id.scylla.com, hostId=null, hashCode=34c36d78): [com.datastax.oss.driver.api.core.connection.ConnectionInitException: [s0|control|id: 0xa111f12e, L:/127.0.0.1:33510 - R:/127.0.0.1:443] Protocol initialization request, step 1 (OPTIONS): failed to send request (javax.net.ssl.SSLHandshakeException: PKIX path validation failed: java.security.cert.CertPathValidatorException: signature check failed)]
	at com.datastax.oss.driver.api.core.scyllacloud.ScyllaCloudMultiNodeIT.connect_w_simple_operations_protocol_v4(ScyllaCloudMultiNodeIT.java:59)
```

**Comment by avikivity** [comment]
Note, we should adopt a waterfall procedure. First apply fixes/features on the main branch, then selectively backport to branches.

Starting with the older branch means that there is a window where someone can upgrade from an older branch with the fix/feature, to a newer branch without the fix/feature and be exposed to a regression.

**Comment by avelanarius** [comment]
> Note, we should adopt a waterfall procedure. First apply fixes/features on the main branch, then selectively backport to branches.
> 
> Starting with the older branch means that there is a window where someone can upgrade from an older branch with the fix/feature, to a newer branch without the fix/feature and be exposed to a regression.

The situation is a bit different in Java Driver. We essentially have two “master”s - scylla-3.x and scylla-4.x, as those are essentially two different drivers not sharing much of the codebase.

The older branches in this repo are branches like scylla-3.7.2.x and we very rarely backport there.

**Comment by avelanarius** [comment]
I should better document this organization and clean up unrelated branches (remnants of upstream Datastax repo)

**Comment by mykaul** [comment]
What's the latest status of this PR?

**Comment by mykaul** [comment]
> What's the latest status of this PR?

@avelanarius - ping

**Comment by Bouncheck** [comment]
Closing. In case the topic of serverless returns, the code can be checked out at 4.x-serverless-feature

**Pull request closed without merging**
