### PR TITLE
docs: trigger theme update

### PR DESCRIPTION
**Pull request by dgarcia360**
This PR will trigger the installation of the latest docs theme, including the Scylla Summit top bar. It also:

- Updates the copyright year automatically https://github.com/scylladb/sphinx-scylladb-theme/pull/83
- Fixes make non latest page clearer https://github.com/scylladb/sphinx-scylladb-theme/pull/74
- Adds poetry.lock (autogenerated) to .gitignore

@tzach This PR includes all the changes in one commit to follow the repository's policy of keeping all the documentation changes in the minimum number of commits as possible.

### CODE REVIEW

**Comment by dgarcia360** [comment]
@lauranovich @tzach Please review

**Comment by lauranovich** [comment]
Screenshot from 2021-01-05 16-48-53
odd rendering going on here

**Comment by lauranovich** [comment]
The PR builds with no errors, but I am not sure if
1 - there is supposed to be more than one version
2- if multiversion is supported for this project

**Comment by dgarcia360** [comment]
> odd rendering going on here 

I couldn't reproduce this issue, did you manage to fix it?

>1 - there is supposed to be more than one version
> 2- if multiversion is supported for this project

Multiversion is enabled but only one version is listed (``latest`` branch). We can list more versions here: https://github.com/scylladb/java-driver/blob/latest/docs/source/conf.py#L196-L198

**Comment by lauranovich** [comment]
the rendering issue i see when I ``make preview``
with ``make multiversion ``I don't see it but the thing is, there should be no difference.

**Comment by dgarcia360** [comment]
I managed to reproduce the issue. It's not related to this PR because it also happens in the ``latest`` branch but with the copybutton extension and markdown support. I've opened a separate issue to keep track of it: https://github.com/scylladb/sphinx-scylladb-theme/issues/101

**Comment by lauranovich** [comment]
ok then we can merge this

**Pull request merged**
